/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { CardDef } from '../types/game';

export const OFFICE_CARDS: Record<string, CardDef> = {
  laptop: {
    type: 'laptop',
    name: 'Laptop',
    iconName: 'Laptop',
    emoji: '💻',
    bgGradient: 'from-blue-600/30 via-blue-500/15 to-indigo-600/30',
    borderColor: 'border-blue-500/50 hover:border-blue-400',
    textColor: 'text-blue-400',
    description: 'Workstation powerhouse for code, spreadsheets, and endless tabs.',
  },
  coffee: {
    type: 'coffee',
    name: 'Coffee',
    iconName: 'Coffee',
    emoji: '☕',
    bgGradient: 'from-amber-600/30 via-amber-500/15 to-orange-600/30',
    borderColor: 'border-amber-500/50 hover:border-amber-400',
    textColor: 'text-amber-400',
    description: 'Triple-shot espresso fuel that powers through Monday standups.',
  },
  plant: {
    type: 'plant',
    name: 'Plant',
    iconName: 'Sprout',
    emoji: '🪴',
    bgGradient: 'from-emerald-600/30 via-emerald-500/15 to-teal-600/30',
    borderColor: 'border-emerald-500/50 hover:border-emerald-400',
    textColor: 'text-emerald-400',
    description: 'Desk succulent bringing oxygen, calm, and thriving office vibes.',
  },
  task: {
    type: 'task',
    name: 'Task Board',
    iconName: 'ClipboardCheck',
    emoji: '📋',
    bgGradient: 'from-violet-600/30 via-purple-500/15 to-indigo-600/30',
    borderColor: 'border-violet-500/50 hover:border-violet-400',
    textColor: 'text-violet-400',
    description: 'Sprint backlog cards prioritized to absolute perfection.',
  },
  headphones: {
    type: 'headphones',
    name: 'Headphones',
    iconName: 'Headphones',
    emoji: '🎧',
    bgGradient: 'from-rose-600/30 via-pink-500/15 to-purple-600/30',
    borderColor: 'border-rose-500/50 hover:border-rose-400',
    textColor: 'text-rose-400',
    description: 'Noise-cancelling sanctuary for deep focus and lo-fi beats.',
  },
  phone: {
    type: 'phone',
    name: 'Phone',
    iconName: 'Smartphone',
    emoji: '📱',
    bgGradient: 'from-cyan-600/30 via-sky-500/15 to-blue-600/30',
    borderColor: 'border-cyan-500/50 hover:border-cyan-400',
    textColor: 'text-cyan-400',
    description: 'Direct hotfix line and executive meme distribution channel.',
  },
  pen: {
    type: 'pen',
    name: 'Executive Pen',
    iconName: 'PenTool',
    emoji: '✒️',
    bgGradient: 'from-yellow-600/30 via-amber-500/15 to-yellow-500/30',
    borderColor: 'border-yellow-500/50 hover:border-yellow-400',
    textColor: 'text-yellow-400',
    description: 'Heavy metal rollerball for contract approvals and sticky notes.',
  },
  email: {
    type: 'email',
    name: 'Email',
    iconName: 'Mail',
    emoji: '✉️',
    bgGradient: 'from-sky-600/30 via-blue-500/15 to-cyan-600/30',
    borderColor: 'border-sky-500/50 hover:border-sky-400',
    textColor: 'text-sky-400',
    description: 'That email that definitely replaced an unnecessary 1-hour meeting.',
  },
  files: {
    type: 'files',
    name: 'Files',
    iconName: 'FolderKanban',
    emoji: '📁',
    bgGradient: 'from-fuchsia-600/30 via-pink-500/15 to-rose-600/30',
    borderColor: 'border-fuchsia-500/50 hover:border-fuchsia-400',
    textColor: 'text-fuchsia-400',
    description: 'Archived project documentation and architecture schematics.',
  },
  idcard: {
    type: 'idcard',
    name: 'ID Badge',
    iconName: 'BadgeCheck',
    emoji: '🪪',
    bgGradient: 'from-teal-600/30 via-emerald-500/15 to-cyan-600/30',
    borderColor: 'border-teal-500/50 hover:border-teal-400',
    textColor: 'text-teal-400',
    description: 'All-access security badge to the rooftop lounge and snack pantry.',
  },
  keyboard: {
    type: 'keyboard',
    name: 'Keyboard',
    iconName: 'Keyboard',
    emoji: '⌨️',
    bgGradient: 'from-indigo-600/30 via-violet-500/15 to-blue-600/30',
    borderColor: 'border-indigo-500/50 hover:border-indigo-400',
    textColor: 'text-indigo-400',
    description: 'Mechanical clicky switches typing out thousand-line pull requests.',
  },
  mouse: {
    type: 'mouse',
    name: 'Ergo Mouse',
    iconName: 'Mouse',
    emoji: '🖱️',
    bgGradient: 'from-lime-600/30 via-emerald-500/15 to-teal-600/30',
    borderColor: 'border-lime-500/50 hover:border-lime-400',
    textColor: 'text-lime-400',
    description: 'Vertical ergonomic wireless mouse engineered for precision clicks.',
  },
  monitor: {
    type: 'monitor',
    name: 'Ultrawide',
    iconName: 'Monitor',
    emoji: '🖥️',
    bgGradient: 'from-blue-700/30 via-cyan-500/15 to-indigo-700/30',
    borderColor: 'border-blue-400/50 hover:border-blue-300',
    textColor: 'text-blue-300',
    description: '49-inch curved monitor accommodating 8 browser windows side by side.',
  },
  notebook: {
    type: 'notebook',
    name: 'Notebook',
    iconName: 'BookOpen',
    emoji: '📓',
    bgGradient: 'from-orange-600/30 via-amber-500/15 to-yellow-600/30',
    borderColor: 'border-orange-500/50 hover:border-orange-400',
    textColor: 'text-orange-400',
    description: 'Dot-grid journal filled with system designs and brainstorm sketches.',
  },
  backpack: {
    type: 'backpack',
    name: 'Commuter Pack',
    iconName: 'Backpack',
    emoji: '🎒',
    bgGradient: 'from-slate-600/30 via-slate-500/15 to-zinc-600/30',
    borderColor: 'border-slate-500/50 hover:border-slate-400',
    textColor: 'text-slate-300',
    description: 'Waterproof commuter backpack carrying all tech gear safely.',
  },
  sticky_note: {
    type: 'sticky_note',
    name: 'Sticky Note',
    iconName: 'FileText',
    emoji: '📝',
    bgGradient: 'from-yellow-500/30 via-amber-400/15 to-yellow-600/30',
    borderColor: 'border-yellow-400/50 hover:border-yellow-300',
    textColor: 'text-yellow-300',
    description: 'Bright canary yellow reminder stuck firmly on the monitor frame.',
  },
  stapler: {
    type: 'stapler',
    name: 'Red Stapler',
    iconName: 'Paperclip',
    emoji: '📎',
    bgGradient: 'from-red-600/30 via-rose-500/15 to-red-700/30',
    borderColor: 'border-red-500/50 hover:border-red-400',
    textColor: 'text-red-400',
    description: 'The legendary red desktop stapler that nobody is allowed to borrow.',
  },
  whiteboard: {
    type: 'whiteboard',
    name: 'Whiteboard',
    iconName: 'BarChart3',
    emoji: '📊',
    bgGradient: 'from-teal-600/30 via-cyan-500/15 to-emerald-600/30',
    borderColor: 'border-teal-500/50 hover:border-teal-400',
    textColor: 'text-teal-400',
    description: 'Floor-to-ceiling glass board covered in quarterly roadmaps.',
  },
  water_bottle: {
    type: 'water_bottle',
    name: 'Insulated Bottle',
    iconName: 'CupSoda',
    emoji: '🧴',
    bgGradient: 'from-cyan-600/30 via-blue-500/15 to-teal-600/30',
    borderColor: 'border-cyan-500/50 hover:border-cyan-400',
    textColor: 'text-cyan-300',
    description: 'Hydro flask keeping ice cold throughout 8 hours of sprint work.',
  },
  desklamp: {
    type: 'desklamp',
    name: 'Desk Lamp',
    iconName: 'Lightbulb',
    emoji: '💡',
    bgGradient: 'from-amber-500/30 via-yellow-400/15 to-orange-500/30',
    borderColor: 'border-amber-400/50 hover:border-amber-300',
    textColor: 'text-amber-300',
    description: 'Warm ambient LED light illuminating late-night project launches.',
  },
  snack: {
    type: 'snack',
    name: 'Snack Stash',
    iconName: 'Cookie',
    emoji: '🥨',
    bgGradient: 'from-amber-700/30 via-orange-600/15 to-yellow-700/30',
    borderColor: 'border-amber-600/50 hover:border-amber-500',
    textColor: 'text-amber-400',
    description: 'Secret drawer stash of dried fruit, nuts, and dark chocolate.',
  },
  clock: {
    type: 'clock',
    name: 'Desk Clock',
    iconName: 'Clock',
    emoji: '⏰',
    bgGradient: 'from-red-600/30 via-orange-500/15 to-amber-600/30',
    borderColor: 'border-red-500/50 hover:border-red-400',
    textColor: 'text-red-400',
    description: 'Pomodoro timer ticking down the final seconds before sprint cutoff.',
  },
  chair: {
    type: 'chair',
    name: 'Ergo Chair',
    iconName: 'Armchair',
    emoji: '🪑',
    bgGradient: 'from-indigo-700/30 via-blue-600/15 to-slate-700/30',
    borderColor: 'border-indigo-500/50 hover:border-indigo-400',
    textColor: 'text-indigo-400',
    description: 'Lumbar-supported mesh throne keeping posture prime all day.',
  },
  glasses: {
    type: 'glasses',
    name: 'Blue Light Specs',
    iconName: 'Glasses',
    emoji: '👓',
    bgGradient: 'from-violet-600/30 via-indigo-500/15 to-purple-600/30',
    borderColor: 'border-violet-500/50 hover:border-violet-400',
    textColor: 'text-violet-400',
    description: 'Amber-tinted blue light filters saving retinas from monitor glare.',
  },
  trophy: {
    type: 'trophy',
    name: 'MVP Award',
    iconName: 'Trophy',
    emoji: '🏆',
    bgGradient: 'from-yellow-500/30 via-amber-400/15 to-orange-500/30',
    borderColor: 'border-yellow-400/50 hover:border-yellow-300',
    textColor: 'text-yellow-300',
    description: 'Quarterly team MVP golden trophy proudly displayed on the shelf.',
  },
  calculator: {
    type: 'calculator',
    name: 'Calculator',
    iconName: 'Calculator',
    emoji: '🔢',
    bgGradient: 'from-emerald-700/30 via-teal-600/15 to-slate-700/30',
    borderColor: 'border-emerald-500/50 hover:border-emerald-400',
    textColor: 'text-emerald-400',
    description: 'Solar-powered financial calculator balancing department budgets.',
  },
  usb: {
    type: 'usb',
    name: 'SSD Drive',
    iconName: 'HardDrive',
    emoji: '💾',
    bgGradient: 'from-purple-700/30 via-indigo-600/15 to-slate-800/30',
    borderColor: 'border-purple-500/50 hover:border-purple-400',
    textColor: 'text-purple-300',
    description: 'High-speed external SSD housing gigabytes of model checkpoints.',
  },
  fan: {
    type: 'fan',
    name: 'USB Fan',
    iconName: 'Wind',
    emoji: '💨',
    bgGradient: 'from-sky-500/30 via-cyan-400/15 to-blue-500/30',
    borderColor: 'border-sky-400/50 hover:border-sky-300',
    textColor: 'text-sky-300',
    description: 'Quiet brushless desk fan circulating cool breeze across workspace.',
  },
  printer: {
    type: 'printer',
    name: 'Office Printer',
    iconName: 'Printer',
    emoji: '🖨️',
    bgGradient: 'from-slate-600/30 via-slate-500/15 to-zinc-600/30',
    borderColor: 'border-slate-400/50 hover:border-slate-300',
    textColor: 'text-slate-300',
    description: 'High-output network laser printer spitting out conference badges.',
  },
  calendar: {
    type: 'calendar',
    name: 'Wall Calendar',
    iconName: 'Calendar',
    emoji: '📅',
    bgGradient: 'from-rose-600/30 via-orange-500/15 to-amber-600/30',
    borderColor: 'border-rose-500/50 hover:border-rose-400',
    textColor: 'text-rose-400',
    description: 'Wall planner marking release freeze dates and company hackathons.',
  },
  badge: {
    type: 'badge',
    name: 'Service Medal',
    iconName: 'Award',
    emoji: '🎖️',
    bgGradient: 'from-amber-600/30 via-yellow-500/15 to-orange-600/30',
    borderColor: 'border-amber-400/50 hover:border-amber-300',
    textColor: 'text-amber-300',
    description: 'Five-year veteran pin awarded during annual all-hands celebrations.',
  },
  headset: {
    type: 'headset',
    name: 'Call Headset',
    iconName: 'Mic',
    emoji: '🎙️',
    bgGradient: 'from-cyan-600/30 via-teal-500/15 to-blue-600/30',
    borderColor: 'border-cyan-400/50 hover:border-cyan-300',
    textColor: 'text-cyan-300',
    description: 'Studio boom-mic headset delivering broadcast-grade voice clarity.',
  },
  briefcase: {
    type: 'briefcase',
    name: 'Briefcase',
    iconName: 'Briefcase',
    emoji: '💼',
    bgGradient: 'from-amber-800/30 via-amber-700/15 to-stone-800/30',
    borderColor: 'border-amber-700/50 hover:border-amber-600',
    textColor: 'text-amber-500',
    description: 'Classic leather attache case for board meeting presentations.',
  },
  bell: {
    type: 'bell',
    name: 'Reception Bell',
    iconName: 'Bell',
    emoji: '🔔',
    bgGradient: 'from-yellow-600/30 via-amber-500/15 to-yellow-700/30',
    borderColor: 'border-yellow-500/50 hover:border-yellow-400',
    textColor: 'text-yellow-400',
    description: 'Brass reception bell ringing whenever a team hits quarterly targets.',
  },
};

export const DEFAULT_ENABLED_CARD_TYPES = Object.keys(OFFICE_CARDS);

export function getCardDef(type: string): CardDef {
  return (
    OFFICE_CARDS[type] || {
      type,
      name: type.charAt(0).toUpperCase() + type.slice(1),
      iconName: 'Sparkles',
      emoji: '🎴',
      bgGradient: 'from-slate-700/30 to-slate-800/30',
      borderColor: 'border-slate-600/50',
      textColor: 'text-slate-300',
      description: 'Special office item card.',
    }
  );
}
